### ISSUE TITLE
问题请教：伪标签质量的重要性

### ISSUE THREAD

**Issue by HRanWang** [GuoleiSun/MCIS_wsss#4]
Hi，guolei：
找不到邮箱等联系方式，固来这里请教^^
想问下你有没有看过生成的伪标签的mIoU有多少，伪标签质量的好坏程度对最后的分割精度影响有多大呢？
想请教你有没有这方面的研究和看法~

**Comment by zerodohero** [comment]
在主页面下面有，还有建议用英文问

**Comment by HRanWang** [comment]
find it! thanks^^

---------- Origin message ----------
>From："zerodohero" <notifications@github.com>
>To："GuoleiSun/MCIS_wsss" <MCIS_wsss@noreply.github.com>
>Subject：Re:_[GuoleiSun/MCIS_wsss]_问题请教：伪标签质量的重要性_(#4)
>Date：2020-09-26 21:44:03

在主页面下面有，还有建议用英文问

**Comment by zerodohero** [comment]
![image](https://user-images.githubusercontent.com/38395598/94343130-a0c76700-0048-11eb-8c8b-5aa68577ea6b.png)
In the bottom

**Comment by aoyanl** [comment]
hello，I also want to know the performance of the pseudo label.Due to there are many pixels marked 255，is it meaningful to evaluate the miou of pseudo labels？can you share some opinions with me？

**Comment by GuoleiSun** [comment]
Hello, thanks for your interest. We didn't evaluate the miou of pseudo labels since there are ignored pixels (255). Note that in wsss problem, many previous methods have ignored pixels (255) when generating pseudo labels. As a result, we think the evaluation of pseudo labels is inaccurate and may not reflect the final performance.
